Repository Couple-App-Project/couple-app-project-frontend, pull requests merged in 2022-12, with the labels that each got.

#13 [feature] : 토큰 처리
  feature/home/components/Profile.tsx
  feature/home/screen/ScreenHome.tsx
  feature/login/queries/apiKey.ts
  feature/login/queries/mutationFn.tsx
  feature/login/queries/mutationFn/mutationFn.tsx
  feature/login/queries/queryFn.tsx
  feature/login/screen/ScreenLogin.tsx
  pages/index.tsx
  utils/api.ts
Labels: ✨ Feature, 📌 To Develop

#11 [feature] : 유효성 검사 및 커스텀 훅 추가
  feature/signUp/hooks/useErrorField.ts
  feature/signUp/hooks/useInput.ts
  feature/signUp/modules/variables/regExp.ts
  feature/signUp/queries/apiKeys.ts
  feature/signUp/queries/mutationFn/useMutationEmailCheck.ts
  feature/signUp/screen/ScreenSignUp.tsx
  feature/signUp/types/fieldErrtype.ts
  feature/signUp/types/isErrorType.ts
  feature/signUp/types/useErrorFieldType.ts
  feature/signUp/types/useInputType.ts
Labels: ✨ Feature, 📌 To Develop

#14 [Fix] : 타입 에러 해결
  feature/signUp/hooks/useErrorField.ts
  feature/signUp/types/isErrorType.ts
  feature/signUp/types/useErrorFieldType.ts
Labels: 🐞 Fix

#16 [Feature] : 캘린더 메인 퍼블리싱
  feature/calender/components/CalenderMain.tsx
  feature/calender/components/index.ts
  feature/calender/screen/ScreenCalendar.tsx
  package.json
  yarn.lock
Labels: ✨ Feature, 📌 To Develop

#19 [Feat] 설정 페이지 구현
  feature/settings/screen/ScreenSettings.tsx
  package-lock.json
  pages/settings/index.tsx
  yarn.lock
Labels: ✨ Feature, 📌 To Develop

#18 [Feat] : 날짜 선택 로직 추가
  feature/calender/components/CalenderMain.tsx
Labels: ✨ Feature

#21 [Fix] : uppercase 에러 해결
  feature/onboarding/types/sliderPropsType.ts
  feature/signUp/types/isErrorType.ts
  feature/signUp/types/useInputType.ts
  types/staticImageDataType.ts
Labels: 🐞 Fix

#20 [Feat] : 다이어리 페이지 추가
  feature/diary/screen/ScreenDiary.tsx
  pages/diary/index.tsx
Labels: ✨ Feature

#23 [Feat]: login 페이지 api 연결
  .gitignore
  feature/login/queries/action.ts
  feature/login/queries/apiKey.ts
  feature/login/queries/mutationFn/mutationFn.tsx
  feature/login/screen/ScreenLogin.tsx
  utils/api.ts
  utils/enum.ts
Labels: ✨ Feature, 📂 Config, 📌 To Develop
