Repository Couple-App-Project/couple-app-project-frontend, pull requests merged in 2023-02, with the labels that each got.

#29 [Feat]: access/refresh 토큰 세팅
  feature/home/queries/mutationFn/mutationFn.tsx
  feature/login/queries/mutationFn/mutationFn.tsx
  package-lock.json
  pages/_app.tsx
  pages/index.tsx
  utils/api.ts
  yarn.lock
Labels: 📂 Config, 📌 To Develop

#31 [Feat] : 회원가입 및 커플 정보 레이아웃 추가 및 캘린더 조회 추가
  components/ElButton.tsx
  components/ElInput.tsx
  components/index.ts
  feature/calender/components/CalenderAddButton.tsx
  feature/calender/components/CalenderDayDetail.tsx
  feature/calender/components/CalenderMain.tsx
  feature/calender/components/index.ts
  feature/calender/queries/apiKeys.ts
  feature/calender/queries/queryFn/useQueryCalenders.ts
  feature/calender/screen/ScreenCalendar.tsx
  feature/calender/types/CalenderMainPropsType.ts
  feature/coupleCode/components/CoupleCodeForm.tsx
  feature/coupleCode/queries/apiKeys.ts
  feature/coupleCode/queries/mutationFn/useMutationCoupleConnent.ts
  feature/coupleCode/screen/ScreenCoupleCode.tsx
  feature/signUp/components/SignUpForm.tsx
  feature/signUp/queries/apiKeys.ts
  feature/signUp/queries/queryFn/index.ts
  feature/signUp/queries/queryFn/useQueryEmailCheck.ts
  feature/signUp/queries/queryKerys.ts
  feature/signUp/screen/ScreenSignUp.tsx
  feature/signUp/types/FormPropsType.ts
  layouts/Device.tsx
  layouts/StepLayout.tsx
  next-svg.d.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  public/images/icons/back.svg
  public/images/icons/close.svg
  public/images/icons/copy.svg
  public/images/icons/drop-down.svg
  public/images/icons/heart-step-01.svg
  public/images/icons/heart-step-02.svg
  public/images/icons/search.svg
  public/images/icons/share.svg
  recoil/calendersState.ts
  styles/colors.ts
  styles/globals.css
  styles/reset.css
  tsconfig.json
  types/CalendersStateType.ts
  utils/deviceDetector.ts
  yarn.lock
Labels: ✨ Feature, 📌 To Develop

#32 [refactor]: icons 위치 변경
  feature/calender/components/CalendarForm.tsx
  public/icons/calendar.svg
  public/icons/cancel.svg
  public/icons/clock.svg
  public/icons/marker-pin.svg
  public/icons/memo.svg
  public/icons/trash.svg
Labels: ♻️ Refactor, 📌 To Develop

#33 [feat/style]: 캘린더 수정 페이지 api 보완/UI
  components/Grid.tsx
  feature/calender/components/Button.tsx
  feature/calender/components/CalendarForm.tsx
  feature/calender/components/FormInput.tsx
  feature/calender/queries/apiKeys.ts
  feature/calender/queries/queryFn/useQueryCalendarDetail.ts
  feature/login/screen/ScreenLogin.tsx
  package-lock.json
  styles/fontTheme.ts
  utils/api.ts
Labels: 🎨 Style, ✨ Feature, 📌 To Develop

#34 [Style, Feat] 회원가입, 커플 코드, 커플 정보, 캘린더 ui 완료 및 캘린더 로직 추가
  components/ElButton.tsx
  components/ElInput.tsx
  feature/calender/components/CalendarMain/Calendar.tsx
  feature/calender/components/CalendarMain/CalendarAddButton.tsx
  feature/calender/components/CalendarMain/CalendarCaption.tsx
  feature/calender/components/CalendarMain/CalendarDay.tsx
  feature/calender/components/CalendarMain/CalendarDayDetail.tsx
  feature/calender/components/CalenderAddButton.tsx
  feature/calender/components/CalenderDayDetail.tsx
  feature/calender/components/CalenderMain.tsx
  feature/calender/components/index.ts
  feature/calender/modules/functions/changeGetDay.ts
  feature/calender/modules/functions/dayArray.ts
  feature/calender/modules/functions/index.ts
  feature/calender/modules/functions/isSunday.ts
  feature/calender/screen/ScreenCalendar.tsx
  feature/calender/types/CalendarMainPropsType.ts
  feature/coupleCode/components/CoupleCodeForm.tsx
  feature/coupleInfo/components/CoupleInfoForm.tsx
  feature/coupleInfo/components/index.ts
  feature/coupleInfo/screen/ScreenCoupleInfo.tsx
  feature/signUp/components/SignUpForm.tsx
  feature/signUp/queries/queryFn/useQueryEmailCheck.ts
  feature/signUp/screen/ScreenSignUp.tsx
  layouts/StepLayout.tsx
  pages/_app.tsx
  public/images/icons/add-button.svg
  public/images/icons/heart-step-01.svg
  public/images/icons/heart-step-02.svg
  public/images/illustrations/calendar.svg
  styles/colors.ts
  styles/fontTheme.ts
  styles/globals.css
  styles/theme.ts
  types/CalendersStateType.ts
  utils/api.ts
Labels: 🎨 Style, ✨ Feature, 📌 To Develop

#35 [Style]: 홈화면 UI 작업
  components/Grid.tsx
  feature/calender/components/CalendarForm.tsx
  feature/common/components/BottomNavi.tsx
  feature/home/components/Modal.tsx
  feature/home/components/ModalBackground.tsx
  feature/home/components/ModalTodayComment.tsx
  feature/home/components/UpcomingSchedule.tsx
  feature/home/screen/ScreenHome.tsx
  feature/login/screen/ScreenLogin.tsx
  public/icons/birthday_pic.png
  public/icons/calendar_pic.png
  public/icons/camera.svg
  public/icons/cancel.svg
  public/icons/chevron-right.svg
  public/icons/heart.svg
  public/icons/notification.svg
  public/icons/paint.svg
  public/icons/pencil.svg
  public/icons/picture.svg
  styles/fonts.css
  styles/theme.ts
  utils/utils.ts
Labels: 🎨 Style, 📌 To Develop

#36 [Feat] : 커플 정보 api, 캘린더 검색 api 연결
  feature/calender/components/CalendarMain/CalendarCaption.tsx
  feature/calender/components/CalendarMain/CalendarDayDetail.tsx
  feature/calender/components/CalendarMain/CalendarSearch.tsx
  feature/calender/components/index.ts
  feature/calender/queries/apiKeys.ts
  feature/calender/queries/queryFn/index.ts
  feature/calender/queries/queryFn/useQueryCalendarSearch.ts
  feature/calender/queries/queryFn/useQueryCalendars.ts
  feature/calender/queries/queryKeys.ts
  feature/calender/screen/ScreenCalendar.tsx
  feature/calender/types/CalendarMainPropsType.ts
  feature/calender/types/CalendarParamsType.ts
  feature/coupleCode/components/CoupleCodeForm.tsx
  feature/coupleInfo/components/CoupleInfoForm.tsx
  feature/coupleInfo/queries/apiKeys.ts
  feature/coupleInfo/queries/mutationFn/index.ts
  feature/coupleInfo/queries/mutationFn/useMutationCoupleInfo.ts
  feature/coupleInfo/screen/ScreenCoupleInfo.tsx
  feature/signUp/components/SignUpForm.tsx
  layouts/StepLayout.tsx
  pages/_app.tsx
  pages/index.tsx
  public/images/icons/arrow-back.svg
  recoil/isSearchState.ts
Labels: ✨ Feature

#38 [Style] : calendar search ui 완료
  feature/calender/components/Button.tsx
  feature/calender/components/CalendarMain/CalendarCaption.tsx
  feature/calender/components/CalendarMain/CalendarDayDetail.tsx
  feature/calender/components/CalendarMain/CalendarSearch.tsx
  feature/calender/components/CalendarSearch/CalendarSearch.tsx
  feature/calender/components/CalendarSearch/SearchInput.tsx
  feature/calender/components/CalendarSearch/SearchList.tsx
  feature/calender/components/CalendarSearch/SearchType.tsx
  feature/calender/components/index.ts
  feature/calender/screen/ScreenCalendar.tsx
  feature/calender/types/CalendarParamsType.ts
  feature/calender/types/CalendarSearchPropsType.ts
  pages/calendar/search.tsx
  recoil/isSearchState.ts
Labels: 🎨 Style

#37 [Feature]: home ui/error 수정
  feature/calender/components/CalendarForm.tsx
  feature/calender/components/FormInput.tsx
  feature/calender/queries/apiKeys.ts
  feature/calender/queries/mutationFn/useMutationDeleteCalendar.ts
  feature/calender/queries/queryFn/useQueryCalendarDetail.ts
  feature/common/components/BottomNavi.tsx
  feature/home/components/ModalBackground.tsx
  feature/home/queries/apiKey.ts
  feature/home/queries/mutationFn/useMutationComment.ts
  feature/home/screen/ScreenHome.tsx
  pages/_app.tsx
  pages/index.tsx
  public/icons/calendar_fill.svg
  public/icons/check-small.svg
  public/icons/home.svg
  public/icons/paint.svg
  public/icons/rect_heart.svg
  public/icons/user.svg
  utils/api.ts
Labels: 🐞 Fix, 🎨 Style, 📌 To Develop
