Repository Couple-App-Project/couple-app-project-frontend, pull requests merged in 2023-03, with the labels that each got.

#40 [Feat]: 다이어리 조회, 배경색상/사진 파트
  feature/coupleInfo/queries/apiKeys.ts
  feature/diary/components/DiaryCard.tsx
  feature/diary/queries/apiKeys.ts
  feature/diary/queries/queryFn/useQueryDiary.ts
  feature/diary/queries/queryKeys.ts
  feature/diary/screen/ScreenDiary.tsx
  feature/home/components/ModalBackground.tsx
  feature/home/screen/ScreenHome.tsx
  feature/home/types/CoupleInfo.ts
  public/icons/bookmark.svg
Labels: ✨ Feature, 📌 To Develop

#41 [Feat, Format] : 캘린더, 다이어리 연결 및 다이어리 CUD
  feature/calender/components/CalendarForm.tsx
  feature/calender/components/calendarMain/Calendar.tsx
  feature/calender/components/calendarMain/CalendarAddButton.tsx
  feature/calender/components/calendarMain/CalendarCaption.tsx
  feature/calender/components/calendarMain/CalendarDay.tsx
  feature/calender/components/calendarMain/CalendarDayDetail.tsx
  feature/calender/components/calendarSearch/CalendarSearch.tsx
  feature/calender/components/calendarSearch/SearchInput.tsx
  feature/calender/components/calendarSearch/SearchList.tsx
  feature/calender/components/calendarSearch/SearchType.tsx
  feature/calender/components/index.ts
  feature/calender/modules/functions/index.ts
  feature/calender/types/CalendarSearchPropsType.ts
  feature/diary/components/common/Content.tsx
  feature/diary/components/detail/DiaryDetail.tsx
  feature/diary/components/index.ts
  feature/diary/components/register/DiaryRegister.tsx
  feature/diary/components/register/RegisterBar.tsx
  feature/diary/components/register/RegisterContent.tsx
  feature/diary/components/register/RegisterHead.tsx
  feature/diary/hook/useImage.ts
  feature/diary/queries/apiKeys.ts
  feature/diary/queries/mutationFn/index.ts
  feature/diary/queries/mutationFn/useMutationCreateDiary.ts
  feature/diary/queries/mutationFn/useMutationDeleteDiary.ts
  feature/diary/queries/mutationFn/useMutationEditDiary.ts
  feature/diary/queries/queryFn/index.ts
  feature/diary/queries/queryFn/useQueryDiaryDetail.ts
  feature/diary/queries/queryKeys.ts
  hooks/useS3Upload.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/diary/detail/[id].tsx
  pages/diary/register/[id].tsx
  public/images/icons/calendar-icon.svg
  public/images/icons/edit.svg
  public/images/icons/emoticon.svg
  public/images/icons/image-upload.svg
  utils/functions/changeDate.ts
  utils/functions/changeGetDay.ts
  utils/functions/index.ts
  utils/imgInstance.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Format, 📌 To Develop

#42 [fix]: diary 상세 주소 경로 변경
  feature/diary/components/DiaryCard.tsx
Labels: 🐞 Fix, 📌 To Develop

#43 [feature]: 다이어리 CRUD, 기타 수정
  feature/calender/components/CalendarForm.tsx
  feature/calender/components/calendarMain/Calendar.tsx
  feature/calender/components/calendarMain/CalendarAddButton.tsx
  feature/calender/components/calendarMain/CalendarCaption.tsx
  feature/calender/components/calendarMain/CalendarDay.tsx
  feature/calender/components/calendarMain/CalendarDayDetail.tsx
  feature/calender/components/calendarSearch/CalendarSearch.tsx
  feature/calender/components/calendarSearch/SearchInput.tsx
  feature/calender/components/calendarSearch/SearchList.tsx
  feature/calender/components/calendarSearch/SearchType.tsx
  feature/calender/components/index.ts
  feature/calender/modules/functions/index.ts
  feature/calender/types/CalendarSearchPropsType.ts
  feature/coupleInfo/queries/apiKeys.ts
  feature/diary/components/DiaryCard.tsx
  feature/diary/components/common/Content.tsx
  feature/diary/components/detail/DiaryDetail.tsx
  feature/diary/components/index.ts
  feature/diary/components/register/DiaryRegister.tsx
  feature/diary/components/register/RegisterBar.tsx
  feature/diary/components/register/RegisterContent.tsx
  feature/diary/components/register/RegisterHead.tsx
  feature/diary/hook/useImage.ts
  feature/diary/queries/apiKeys.ts
  feature/diary/queries/mutationFn/index.ts
  feature/diary/queries/mutationFn/useMutationCreateDiary.ts
  feature/diary/queries/mutationFn/useMutationDeleteDiary.ts
  feature/diary/queries/mutationFn/useMutationEditDiary.ts
  feature/diary/queries/queryFn/index.ts
  feature/diary/queries/queryFn/useQueryDiary.ts
  feature/diary/queries/queryFn/useQueryDiaryDetail.ts
  feature/diary/queries/queryKeys.ts
  feature/diary/screen/ScreenDiary.tsx
  feature/home/components/ModalBackground.tsx
  feature/home/screen/ScreenHome.tsx
  feature/home/types/CoupleInfo.ts
  hooks/useS3Upload.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/diary/detail/[id].tsx
  pages/diary/register/[id].tsx
  public/icons/bookmark.svg
  public/images/icons/calendar-icon.svg
  public/images/icons/edit.svg
  public/images/icons/emoticon.svg
  public/images/icons/image-upload.svg
  utils/functions/changeDate.ts
  utils/functions/changeGetDay.ts
  utils/functions/index.ts
  utils/imgInstance.ts
  yarn.lock
Labels: ✨ Feature, 📌 To Main

#48 [fix] deploy fix
  feature/calender/types/CalendarParamsType.ts
  pages/index.tsx
Labels: 🐞 Fix, 📂 Config

#54 [Fix/Feature] fix update/배경이미지 등록api
  feature/calender/components/CalendarForm.tsx
  feature/common/components/ModalBackground.tsx
  feature/coupleInfo/queries/apiKeys.ts
  feature/coupleInfo/queries/mutationFn/useMutationCoupleInfo.ts
  feature/coupleInfo/queries/queryFn/useQueryCoupleInfo.ts
  feature/coupleInfo/queries/queryKeys.ts
  feature/diary/queries/apiKeys.ts
  feature/diary/queries/mutationFn/useMutationLabel.ts
  feature/diary/queries/queryFn/useQueryCalendarDiary.ts
  feature/diary/queries/queryKeys.ts
  feature/diary/screen/ScreenDiary.tsx
  feature/home/queries/apiKey.ts
  feature/home/queries/apiKeys.ts
  feature/home/queries/mutationFn/mutationFn.tsx
  feature/home/queries/mutationFn/useMutationCreateBackground.ts
  feature/home/queries/queryFn/useQueryBackground.ts
  feature/home/queries/queryKeys.ts
  feature/home/screen/ScreenHome.tsx
  feature/mypage/queries/apiKey.ts
  feature/mypage/queries/mutationFn/useMutationMypage.tsx
  feature/mypage/queries/mutationFn/useMutationNickname.ts
  feature/mypage/screen/ScreenMypage.tsx
  public/icons/chevron-right.svg
  public/icons/pink-diary.png
  public/icons/plus.svg
Labels: 🐞 Fix, ✨ Feature, 📌 To Develop

#56 [feature]: 홈화면 배너 이미지 변경
  feature/common/components/ModalBackground.tsx
  feature/home/queries/mutationFn/useMutationCreateBackground.ts
  feature/home/screen/ScreenHome.tsx
Labels: ✨ Feature, 📌 To Develop

#58 [style] UI fix
  feature/calender/components/CalendarForm.tsx
  feature/calender/components/FormInput.tsx
  feature/common/components/ModalInput.tsx
  feature/diary/components/DiaryCard.tsx
  feature/diary/screen/ScreenDiary.tsx
  feature/home/screen/ScreenHome.tsx
  feature/mypage/screen/ScreenMypage.tsx
  public/images/background_image.jpg
Labels: 🐞 Fix, 🎨 Style, 📌 To Develop

#61 [fix]: Body2 -> Body_2
  feature/common/components/ModalDate.tsx
  feature/common/components/ModalInput.tsx
Labels: 🐞 Fix, 🎨 Style, 📌 To Develop

#62 Develop
  feature/common/components/ModalDate.tsx
  feature/common/components/ModalInput.tsx
Labels: 🐞 Fix, 📌 To Main
